version: 2.1

jobs:
  test:
    docker:
      - image: cimg/ruby:3.3.4
    steps:
      - checkout
      - restore_cache:
          keys:
            - bundle-{{ checksum "Gemfile.lock" }}
      - run: bundle install
      - save_cache:
          key: bundle-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run: bundle exec rspec
      - run: bundle exec rubocop

workflows:
  test:
    jobs:
      - test
