steps:
  - label: ':ruby: ruby_api_pack_core verify'
    key: 'verify'
    command:
      - 'bundle install'
      - 'bundle exec rspec'
      - 'bundle exec rubocop'
    agents:
      queue: 'default'
    timeout_in_minutes: 15
